[Fix] Taken from not_found check and modified

diff --git a/01_simple_shell_0.1/test_bin2 b/01_simple_shell_0.1/test_bin2
--- a/01_simple_shell_0.1/test_bin2
+++ b/01_simple_shell_0.1/test_bin2
@@ -1,32 +1,31 @@
 #!/bin/bash
 #
-# testing /bin
-# sh output:
-# sh: 1: /bin: Permission denied
+# Check if not found error is correct
 
-command="/bin"
-tmp_file="checker_tmp_file_$RANDOM"
+command="/bin/"
 
 # clean up
 stop_shell
 rm -f $tmp_file
 
-# create a pseudo random file
-touch $tmp_file
-# run command
-echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &
+# send commands
+echo "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &
 
 # wait a little bit
 $SLEEP $SLEEPSECONDS
 
+
 # check the result
-nmatch=`cat $OUTPUTFILE | grep -c "$tmp_file"`
-if [ $nmatch -eq 1 ]; then
-	   print_ok
+echo "$SHELL: 1: /bin: Permission denied" > your_output
+diff -q $ERROROUTPUTFILE your_output
+match=$?
+if [ $match -eq 0 ]; then
+    print_ok
 else
-	   print_ko
+    print_ko
 fi
 
 # clean up
 stop_shell
 rm -f $tmp_file
+rm -f your_output
