[Fix]: help case

diff --git a/06_error_cases_0.4/show_help b/06_error_cases_0.4/show_help
--- a/06_error_cases_0.4/show_help
+++ b/06_error_cases_0.4/show_help
@@ -1,8 +1,8 @@
 #!/bin/bash
 #
-# Test if the shell handles the # character
+# Just check if help runs
 
-command="/bin/ls -l ##a"
+command="help"
 tmp_file="checker_tmp_file_$RANDOM"
 
 # clean up
@@ -11,20 +11,25 @@ rm -f $tmp_file
 
 # create a pseudo random file
 touch $tmp_file
+
 # send commands
-echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &
+echo "$command" | $SHELL > /dev/null 2> $ERROROUTPUTFILE &
 
 # wait a little bit
 $SLEEP $SLEEPSECONDS
 
 # check the result
-nmatch=`cat $OUTPUTFILE | grep -c "$tmp_file"`
-if [ $nmatch -eq 1 ]; then
-	   print_ok
+echo "$SHELL: 1: help: not found" > answer
+diff -q $ERROROUTPUTFILE answer
+match=$?
+if [ $match -eq 0 ]; then
+    print_ok
 else
-	   print_ko
+    print_ko
 fi
+
 
 # clean up
 stop_shell
 rm -f $tmp_file
+rm -f answer
